import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
//import Card from "./components/Card"
import { ClerkProvider } from '@clerk/nextjs'

    

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
      <ClerkProvider>
        <Header/>
       
        <div className="flex flex-col items-center justify-center mt-10 -space-y-4 ">
        <h1 className="text-4xl font-bold text-[#582086] text-center">Get Artistic Prints</h1>

      </div>
      
     
      
    
    
        
        {children}
        </ClerkProvider>
        
        </body>
    </html>
    
  );
}
